name: CI

on:
  push:
    branches: ["main"]

jobs:
  connect-remote:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: "kashishdesai" # PostgreSQL database name
          POSTGRES_USER: "postgres" # PostgreSQL username
          POSTGRES_PASSWORD: "Flender1" # PostgreSQL password
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Use an existing Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
