name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  connect-remote:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.postgres }}
          POSTGRES_PASSWORD: ${{ secrets.Flender1 }}
          POSTGRES_DB: ${{ secrets.kashishdesai }}
        ports:
          - 5433:5433

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: create & configure
        run: |
          touch .env  
          PORT: ${{ secrets.port }} >> .env
          echo DB_NAME=${{ secrets.dbName }} >> .env
          echo DB_USER=${{ secrets.dbUser }} >> .env
          echo DB_PASSWORD=${{ secrets.dbPassword }} >> .env
          echo DB_HOST=${{ secrets.dbPort }} >> .env
          echo DB_DIALECT=${{ secrets.dialect }} >> .env
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
