name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  connect-remote:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DBUSER }}
          POSTGRES_PASSWORD: ${{ secrets.DBPASSWORD }}
          POSTGRES_DB: ${{ secrets.DBNAME }}
        ports:
          - 5432:5433

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Set up .env file
        run: |
          echo PORT=${{ secrets.PORT }} >> .env
          echo DBNAME=${{ secrets.DBNAME }} >> .env
          echo DBUSER=${{ secrets.DBUSER }} >> .env
          echo DBPASSWORD=${{ secrets.DBPASSWORD }} >> .env
          echo DBPORT=${{ secrets.DBPORT }} >> .env
          echo DIALECT=${{ secrets.DIALECT }} >> .env

      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test
          PORT: ${{ secrets.PORT }}
          DBPORT: ${{ secrets.DBPORT }}
          DBNAME: ${{ secrets.DBNAME }}
          DBUSER: ${{ secrets.DBUSER }}
          DBPASSWORD: ${{ secrets.DBPASSWORD }}
          DIALECT: ${{ secrets.DIALECT }}
