name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  connect-remote:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DBUSER }}
          POSTGRES_PASSWORD: ${{ secrets.DBPASSWORD }}
          POSTGRES_DB: ${{ secrets.DBNAME }}
        ports:
          - 5433:5433

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: create & configure
        run: |
          touch .env  
          echo PORT=${{ secrets.PORT }} >> .env
          echo DBNAME=${{ secrets.DBNAME }} >> .env
          echo DBUSER=${{ secrets.DBUSER }} >> .env
          echo DBPASSWORD=${{ secrets.DBPASSWORD }} >> .env
          echo DBPORT=${{ secrets.DBPORT }} >> .env
          echo DIALECT=${{ secrets.DIALECT }} >> .env
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: |
          npm test
        env:
          DBPORT: ${{ secrets.DBPORT }}
          DBNAME: ${{ secrets.DBNAME }}
          DBUSER: ${{ secrets.DBUSER }}
          DBPASSWORD: ${{ secrets.DBPASSWORD }}
          DIALECT: ${{ secrets.DIALECT }}
